### ISSUE TITLE
does not create filelist.txt - prevents repacking

### ISSUE THREAD

**Issue by LordofSandvich** [Wulf2k/DeS-BNDBuild#6]
(As of 7/21/17) Putting in one's own filelist works, as long as all param files are present

It only does this when extracting Gameparam.parambnd and paramdef.bnd however. Other extractions work fine

**Comment by Wulf2k** [comment]
Weird.  I'll look into why it's getting skipped next week, heading out for the weekend right away.

**Comment by LordofSandvich** [comment]
It also only affects previously extracted files. A fresh dvdbnd3.bhd5 is not affected.
Thank you.

**Comment by Wulf2k** [comment]
Not quite sure I follow.

What steps would I take to recreate this?

**Comment by LordofSandvich** [comment]
You would need to acquire a repeatedly repacked file from either previous usage or download (http://www.nexusmods.com/darksouls/mods/1239/? is the mod I made using your tools, for example) and then unpack the file to the point where either paramdef.paramdefbnd or GameParam.parambnd are extracted. In the next stage it should generate a chain of folders, with the first folder FRPG which would normally appear alongside a "filelist.txt", except this file is not present. This always occurs alongside the other glitch I reported.

I think that your tool was not meant for the extensive extracting and rebuilding that I've done with it so I'm not particularly surprised that I'm having a problem. I'd just rather not go through all the work I did all over again, as I wound up losing the unpacked files.

**Comment by LordofSandvich** [comment]
Unhandled exception - Source array was not long enough. Check srcIndex and length, and the array's lower bounds.

Throws this error every time this occurs. Using loosepolygon's edit for Dark Souls did not change this.

**Comment by LordofSandvich** [comment]
New version of DeS-BNDBuild still has this error.

**Comment by loosepolygon** [comment]
Sounds like the dcx corruption bug that I fixed. I'll take a look at more formats.

**Comment by Wulf2k** [comment]
Does it have the error if you (with the newest version, just in case) extract, immediately rebuild, then extract again?

**Comment by LordofSandvich** [comment]
Yes. Both errors are occuring regardless of version used

**Comment by LordofSandvich** [comment]
Can confirm that this error does not occur when using an unmodified version of a bhd5 file, only files that have been extracted, modified, rebuilt, moved, and then extracted again have the error.

*this is seemingly difficult to replicate with the current version, if possible at all. As such the error I am running into is most likely caused by a failure of an old version.

I'm assuming all versions of the BND Rebuilder ignore files not found in a filelist.txt in the case of gameparam.parambnd and related files

**Comment by Wulf2k** [comment]
Can this issue be closed?

**Comment by LordofSandvich** [comment]
I believe so. I'll test it quickly and reopen it if necessary but I think it's clean now.
