### ISSUE TITLE
Partially extracts GameParam.bnd/paramdef.paramdefbnd

### ISSUE THREAD

**Issue by LordofSandvich** [Wulf2k/DeS-BNDBuild#7]
some param files are missing from extraction - only affects previously unpacked files

**Comment by Wulf2k** [comment]
What do you mean by "only affects previously unpacked files"?

**Comment by LordofSandvich** [comment]
If I use the dvdbnd3.bhd5 file from the original install this glitch does not occur; if I use a package previously changed by some version of BND Edit it occurs. Specifically if I rebuild the dvdbnd3 pair in Dark Souls, then any extraction from those two modified files fails. If that helps, great!

**Comment by LordofSandvich** [comment]
To be clear this is Dark Souls, looking at the pull requests I can see that I've been lucky to run into as few errors as I have

**Comment by LordofSandvich** [comment]
Using most recent version, 10 param files are not properly unpacked from gameparam, specifically the last 11 param files (at one point) generated in the filelist. As they appear in filelist.txt, they are:
28,N:\FRPG\data\INTERROOT_win32\param\GameParam\ShopLineupParam.param
29,N:\FRPG\data\INTERROOT_win32\param\GameParam\QwcChange.param
30,N:\FRPG\data\INTERROOT_win32\param\GameParam\QwcJudge.param
31,N:\FRPG\data\INTERROOT_win32\param\GameParam\GameAreaParam.param
32,N:\FRPG\data\INTERROOT_win32\param\GameParam\SkeletonParam.param
33,N:\FRPG\data\INTERROOT_win32\param\GameParam\CalcCorrectGraph.param
36,N:\FRPG\data\INTERROOT_win32\param\GameParam\LockCamParam.param
37,N:\FRPG\data\INTERROOT_win32\param\GameParam\ObjActParam.param
38,N:\FRPG\data\INTERROOT_win32\param\GameParam\HitMtrlParam.param
39,N:\FRPG\data\INTERROOT_win32\param\GameParam\KnockBackParam.param
These are reliably not generated; the missing param files are always these.
In paramdef only the last four are not generated, as they appear in filelist.txt (for some reason previous value is 43,N)
46,N:\FRPG\data\INTERROOT_win32\paramdef\LockCamParam.paramdef
47,N:\FRPG\data\INTERROOT_win32\paramdef\ObjActParam.paramdef
48,N:\FRPG\data\INTERROOT_win32\paramdef\HitMtrlParam.paramdef
49,N:\FRPG\data\INTERROOT_win32\paramdef\KnockBackParam.paramdef

**Comment by Wulf2k** [comment]
Is this still an issue, or does this only occur when unpacking files previously packed with an old version?

**Comment by LordofSandvich** [comment]
It only occurs with previously broken versions. Repacking it fixes it, so as long as the old .param files are intact it is 100% recoverable. Closing.
